config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  constraints subdomain: "saiu" do
    get '', to: 'saiu/claims#new'
    namespace :saiu do
      resources :claims do
        collection do
          get :thanks
        end
      end
    end
  end
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  namespace :widgets do
    resources :keyboards, only: %i[index show new create]
    resources :calendars
  end
  resources :widgets, only: :index

  get '/homma_fights', to: 'video_markup/heroes/fights#index', as: 'video_markup_heroes_fights'
  scope :homma_fights do
    get ':slug', to: 'video_markup/heroes/units#show', constraints: { slug: /unit-.*/ }, as: 'video_markup_heroes_unit'
    get ':slug', to: 'video_markup/heroes/heroes#show', constraints: { slug: /hero-.*/ }, as: 'video_markup_heroes_hero'
    get ':slug', to: 'video_markup/heroes/banks#show', constraints: { slug: /bank-.*/ }, as: 'video_markup_heroes_bank'
  end
  namespace :video_markup do
    resources :videos, only: %i[show new create index]
    resources :moments
    namespace :heroes do
      resources :units, only: %i[index]
      resources :banks, only: %i[index]
      resources :heroes, only: %i[index]
    end
  end
  get '/video_markup', to: 'video_markup#index'
  namespace :strava do
    resources :activities, only: %i[index show] do
      put :sync_details
      put :sync_streams
    end
    resources :syncs, only: %i[create]
  end
  resources :strava, only: :index do
  end
  namespace :sport do
    resources :activities
    namespace :exercises do
      resources :simple_groups, only: %i[index show]
    end
    resources :exercises do
      put :refresh_video_derivatives
    end
  end
  resources :sport, only: :index
  resources :local_markups, only: %i[create index new show] do
    resources :check_points, only: %i[update show index], controller: 'local_markup/check_points'
    get 'result'
  end
  resources :share_links, only: %i[new create show index]
  authenticate :user, lambda { |u| Ability.new(u).can?(:read, :sidekiq) } do
    mount Sidekiq::Web => "/sidekiq"
  end
  telegram_webhook Telegram::ChordQuizController, :chord_quiz
  telegram_webhook Telegram::WebhookController
  telegram_webhook Telegram::MmmPrinterController, :mmm_printer
  post '/yandex/browser/message', to: 'yandex/browser#message'
  post '/yandex/browser', to: 'yandex/browser#create'
  post '/yandex/browser/answer', to: 'yandex/browser#answer'
  get '/yandex/browser/:id', to: 'yandex/browser#show'
  post '/webhooks/twitch', to: 'webhooks#twitch'
  get '/webhooks/twitch', to: 'webhooks#twitch_check'
  post '/webhooks/twitch/:streamer_id', to: 'webhooks#twitch'
  get '/webhooks/twitch/:streamer_id', to: 'webhooks#twitch_check'
  namespace :marusia do
    resources :heroes, only: :create
  end
  namespace :mmm do
    resources :print_requests, only: %i[index update]
  end

  namespace :user do
    resources :merges, only: %i[new create update] do
      collection do
        get "confirm"
      end
    end
  end

  resources :users, only: %i[index show] do
    resources :runs, only: :index, controller: 'users/runs'
  end

  namespace :api do
    namespace :v1 do
      namespace :sport do
        resources :exercises, only: [] do
          collection do
            get :autocomplete
          end
        end
      end
    end
  end
end

app/models/sport.rb
module Sport
  def self.table_name_prefix
    'sport_'
  end
end

app/models/sport/activity.rb
# == Schema Information
#
# Table name: sport_activities
#
#  id               :bigint           not null, primary key
#  name             :string           not null
#  user_id          :bigint
#  started_at       :datetime
#  duration_seconds :bigint
#  kind             :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  enabled          :boolean          default(FALSE), not null
#  og_image_data    :jsonb
#
# Indexes
#
#  index_sport_activities_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Sport::Activity < ApplicationRecord
  has_many :strava_activities, class_name: 'Strava::Activity', dependent: :nullify, foreign_key: :sport_activity_id
  belongs_to :user
  has_many :activity_exercises, class_name: 'Sport::ActivityExercise', dependent: :destroy, foreign_key: :activity_id
  has_many :sorted_activity_exercises, -> { sorted }, class_name: 'Sport::ActivityExercise'
  has_many :exercises, class_name: 'Sport::Exercise', through: :activity_exercises

  accepts_nested_attributes_for :activity_exercises, allow_destroy: true, reject_if: proc { |attributes| attributes.slice('exercise_id', 'exercise').values.all?(&:blank?) }

  def duration
    return nil if duration_seconds.nil?

    Time.at(duration_seconds).gmtime
  end

  def duration=(value)
    self.duration_seconds = nil if value.nil?

    hh, mm, ss = value.split(':').map(&:to_i)
    self.duration_seconds = hh * 3600 + mm * 60 + ss
  end

  attr_accessor :strava_activity_id
  after_create :set_sport_activity_id_to_strava_activity, if: -> { strava_activity_id.present? }

  def set_sport_activity_id_to_strava_activity
    user.strava_activities.find(strava_activity_id).update!(sport_activity_id: id)
  end

  def self.default_kinds
    ['Бег трусцой', 'Бег интервальный', 'Функциональная', 'Велопрогулка']
  end

  def provider_activities
    strava_activities.sort_by(&:strava_id)
  end

  def provider_names
    strava_activities.map(&:provider_name).uniq
  end

  def activity_exercises_with_video
    @__activity_exercises_with_video ||= activity_exercises.to_a.select { |obj| obj.exercise.video_derivatives.present? }
  end

  def og_image_sizes
    width = [(activity_exercises_with_video.size / 1.618).round, 2].max
    height = (activity_exercises_with_video.size.to_f / width.to_f).ceil
    [width, height]
  end

  def generate_montage_image
    tempfile = Tempfile.new ["montage", ".jpg"]
    MiniMagick::Tool::Montage.new do |montage|
      montage.mode 'concatenate'

      montage.background 'none'
      activity_exercises_with_video.each do |activity_exercise|
        montage.resize '200x'
        montage << activity_exercise.exercise.video(:screenshot).download.path
      end

      montage.tile og_image_sizes.join('x')

      montage << tempfile.path
    end
    tempfile
  end

  def refresh_og_image!
    self.og_image = generate_montage_image
    save!
  end

  include OgImageUploader::Attachment(:og_image)

  def title
    [user.name, name].join(' — ')
  end

  def content
    exercises.map(&:name).to_sentence
  end

  def h1
    title
  end

  def keywords
    "тренировка, упражнения, спорт"
  end

  def description
    content
  end

  def og_title
    ['Тренировка', title].join(' — ')
  end

  def robots
  end

  def fullpath
  end
end

app/models/sport/activity_exercise.rb
# == Schema Information
#
# Table name: sport_activity_exercises
#
#  id          :bigint           not null, primary key
#  activity_id :bigint           not null
#  exercise_id :bigint           not null
#  comment     :text
#  position    :bigint           default(0), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_sport_activity_exercises_on_activity_id  (activity_id)
#  index_sport_activity_exercises_on_exercise_id  (exercise_id)
#
# Foreign Keys
#
#  fk_rails_...  (activity_id => sport_activities.id)
#  fk_rails_...  (exercise_id => sport_exercises.id)
#
class Sport::ActivityExercise < ApplicationRecord
  belongs_to :activity, class_name: 'Sport::Activity', required: false
  belongs_to :exercise, class_name: 'Sport::Exercise'

  validates :exercise_id, uniqueness: {scope: :activity_id}

  scope :sorted, -> { order(:position) }

  delegate :video_vertical?, to: :exercise
end

app/models/sport/exercise/simple_group.rb
# == Schema Information
#
# Table name: sport_exercise_simple_groups
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Sport::Exercise::SimpleGroup < ApplicationRecord
  has_many :exercises, class_name: 'Sport::Exercise', foreign_key: :simple_group_id, dependent: :nullify
end

app/controllers/api/v1/sport/exercises_controller.rb
class Api::V1::Sport::ExercisesController < Api::V1Controller
  include AutocompleteController
  def autocomplete
    term, options = ac_options
    records = Sport::Exercise.search(term, **options.merge(load: false))
    render json: records.map { |rec| rec.slice("id", "name", "aliases", "content", "user_id") }
  end
end

app/controllers/sport/activities_controller.rb
class Sport::ActivitiesController < SportController
  breadcrumb 'Тренировки', :sport_activities
  before_action :authenticate_user!, except: %i[show]
  before_action :set_kinds, only: %i[new create edit update]
  before_action :set_activity, only: %i[edit update show]

  def index
    @sport_activities = current_user.sport_activities.reorder(id: :desc).page(params[:page]).per(12)
  end

  def new
    breadcrumb 'Новая', request.fullpath
    @sport_activity = provider_activity&.to_sport_activity || Sport::Activity.new
  end

  def create
    @sport_activity = current_user.sport_activities.new(sport_activity_params)
    @sport_activity.save!
    redirect_to @sport_activity, flash: {success: 'Успех'}
  rescue => e
    flash[:error] = "#{e.class.to_s}\n#{e.message}\n#{e.backtrace.first(4).join("\n")}"
    breadcrumb 'Новая', new_sport_activity_path
    render 'new'
  end

  def show
    @video_js = true
    @page = @sport_activity
    breadcrumb @sport_activity.name, request.fullpath
  end

  def edit
    breadcrumb @sport_activity.name, sport_activity_path(@sport_activity)
    breadcrumb "Редактирование", edit_sport_activity_path(@sport_activity)
  end

  def update
    @sport_activity.update!(sport_activity_params)
    redirect_to @sport_activity, flash: {success: 'Успех'}
  rescue => e
    flash[:error] = "#{e.class.to_s}\n#{e.message}\n#{e.backtrace.first(4).join("\n")}"
    breadcrumb @sport_activity.name, request.fullpath
    render 'edit'
  end

  private
  def provider_activity
    if params[:strava_activity_id]
      return Strava::Activity.find(params[:strava_activity_id])
    end
    nil
  end

  def sport_activity_params
    params.require(:sport_activity).permit(
      :name,
      :strava_activity_id,
      :kind,
      :duration,
      :started_at,
      :enabled,
      activity_exercises_attributes: %i[
        id
        exercise_id
        comment
        _destroy
      ]
    )
  end

  def set_kinds
    @kinds = (current_user.sport_activities.distinct.pluck(:kind) + Sport::Activity.default_kinds).sort.uniq
  end

  def set_activity
    @resource = @sport_activity = Sport::Activity.accessible_by(current_ability).find(params[:id])
  end
end

app/controllers/sport/exercises/simple_groups_controller.rb
class Sport::Exercises::SimpleGroupsController < SportController
  breadcrumb 'Группы упражнений', :sport_exercises_simple_groups
  def index
    @simple_groups = Sport::Exercise::SimpleGroup.all.page(params[:page]).per(12)
  end

  def show
    @simple_group = Sport::Exercise::SimpleGroup.find(params[:id])
    @exercises = @simple_group.exercises.page(params[:page]).per(12)

    @video_js = true
    breadcrumb @simple_group.name, sport_exercises_simple_group_path(@simple_group)
  end
end

app/controllers/sport/exercises_controller.rb
class Sport::ExercisesController < SportController
  breadcrumb 'Упражнения', :sport_exercises
  before_action :authenticate_user!, only: %i[new create edit update]
  before_action :set_exercise, only: %i[edit update show refresh_video_derivatives]
  before_action :load_dictionaries, only: %i[new edit]

  def index
    @video_js = true
    @exercises = Sport::Exercise.all.page(params[:page]).per(12)
  end

  def new
    breadcrumb 'Новое', request.fullpath
    @exercise = Sport::Exercise.new
  end

  def create
    Sport::Exercise.transaction do
      @exercise = current_user.sport_exercises.create!(sport_exercise_params)
    end
    redirect_to @exercise, flash: {success: 'Успех'}
  rescue => e
    flash[:error] = "#{e.class.to_s}\n#{e.message}\n#{e.backtrace.first(4).join("\n")}"
    breadcrumb 'Новое', request.fullpath
    load_dictionaries
    render 'new'
  end

  def show
    @use_vanilla_bootstrap = @video_js = true
    breadcrumb @exercise.name, request.fullpath
  end

  def edit
    breadcrumb @exercise.name, sport_exercise_path(@exercise)
    breadcrumb "Редактирование", request.fullpath
  end

  def update
    authorize! :update, @exercise
    Sport::Exercise.transaction do
      @exercise.update!(sport_exercise_params)
    end
    redirect_to @exercise, flash: {success: 'Успех'}
  rescue => e
    flash[:error] = "#{e.class.to_s}\n#{e.message}\n#{e.backtrace.first(4).join("\n")}"
    load_dictionaries
    breadcrumb @exercise.name, request.fullpath
    render 'edit'
  end

  def refresh_video_derivatives
    authorize! :update, @exercise
    @exercise.video_derivatives!
    @exercise.save!
    flash[:success] = 'Успех'
  rescue => e
    flash[:error] = "#{e.class.to_s}\n#{e.message}\n#{e.backtrace.first(4).join("\n")}"
  ensure
    redirect_back fallback_location: sport_exercise_path(@exercise)
  end

  private
  def sport_exercise_params
    params.require(:sport_exercise).permit(:name, :content, :video, :simple_group_name)
  end

  def set_exercise
    @resource = @exercise = Sport::Exercise.find(params[:id] || params[:exercise_id])
  end

  def load_dictionaries
    @simple_groups = Sport::Exercise::SimpleGroup.pluck(:name)
  end
end

app/controllers/sport_controller.rb
class SportController < ApplicationController
  before_action :authenticate_user!
  breadcrumb 'Спорт', :sport_index

  def index
  end
end

app/controllers/strava/activities_controller.rb
class Strava::ActivitiesController < StravaController
  breadcrumb 'Активности', :strava_activities
  def index
    authenticate_user!
    scope = current_user.strava_activities
    @activities = scope.where(index_where_params).order(strava_id: :desc).page(params[:page]).per(12)
    @strava_types = scope.group(:strava_type).count.to_a.sort_by(&:last).reverse
  end

  def show
    @use_vanilla_bootstrap = true
    @resource = @activity = Strava::Activity.find(params[:id])
    breadcrumb @resource.full_name, strava_activity_path(@resource)
    render_template!
  end

  def sync_details
    sync do |service|
      service.fetch_activity(@activity)
    end
  end

  def sync_streams
    sync do |service|
      service.fetch_streams(@activity)
    end
  end

  private
  def sync
    @resource = @activity = Strava::Activity.find(params[:activity_id])
    identity = current_user.strava_identity
    service = Strava::ActivityService.new(identity)
    yield service
    flash[:success] = 'Данные обновлены'
  rescue ActiveRecord::RecordNotFound => e
    raise e
  rescue => e
    Rails.logger.error(e)
    flash[:error] = "Ошибка #{e.class.to_s}\n#{e.message}\n#{e.backtrace.first(3).join("\n")}"
  ensure
    redirect_back fallback_location: strava_activity_path(@activity)
  end

  def index_where_params
    params.permit(:strava_type)
  end


end

app/views/sport/activities/_activity_exercise_fields.slim
.card.js-activity-exercise-fields
  .card-header.d-flex.justify-content-between
    h2 Упражнение
    = link_to_delete_row(:button, 'js-activity-exercise-fields', class: 'btn btn-danger m-1', type: 'button') do
      i.fas.fa-ban
  .card-body
    = f.input :id, as: :hidden
    = f.input :exercise_id, as: :select, collection: Sport::Exercise.pluck(:name, :id)
    = f.input :comment
    = f.input :_destroy, as: :hidden

app/views/sport/activities/_form.slim
= simple_form_for activity do |f|
  = f.button :submit, class: 'btn btn-success', value: 'Сохранить'
  = f.input :name, label: 'Название', required: true
  = f.input :started_at, as: :datetime, html5: true, label: 'Начало'
  = f.input :duration, as: :time, label: 'Длительность', html5: true, input_html: {step: 1}
  = f.input :kind, as: :combobox, label: "Тип", values: kinds
  = f.input :enabled, label: 'Видна всем посетителям сайта'
  = f.input :strava_activity_id, as: :hidden
  .js-activity_exericises-fields
    = f.simple_fields_for(:activity_exercises, f.object.activity_exercises.try { |collection| collection.presence || collection.new }) do |ae_f|
      = render 'sport/activities/activity_exercise_fields', f: ae_f

  .btn-group
    = link_to_add_row('Добавить упражнение', f, :activity_exercises, 'js-activity_exericises-fields', view_path: 'sport/activities/activity_exercise_fields', class: 'btn btn-primary')
    = f.button :submit, class: 'btn btn-success', value: 'Сохранить'

app/views/sport/activities/_provider_list.slim
- if list.present?
  .list-group
    - list.each do |provider_activity|
      = link_to "#{provider_activity.provider_name} #{provider_activity.kind_human} #{l(provider_activity.started_at, format: :short)}", provider_activity, class: 'list-group-item list-group-item-action'

app/views/sport/activities/_show_actions.slim
- if can?(:update, activity)
  /.btn-group.d-none.d-sm-inline-flex
  .btn-group
    = link_to [:edit, activity], class: 'btn btn-primary m-1', title: 'Редактировать' do
      i.fas.fa-edit

  /.dropdown.d-sm-none
    button.btn.btn-secondary id=dropdown_id data-bs-toggle="dropdown" aria-expanded="false"
      i.fas.fa-ellipsis-v
    ul.dropdown-menu.dropdown-menu-end aria-labelledby=dropdown_id
      li = link_to 'Редактировать', [:edit, activity], class: 'dropdown-item'

app/views/sport/activities/_video_gallery.slim
- if list.present?
  .row.row-cols-2.row-cols-sm-3.row-cols.md-4.mt-2.g-0
    - sort_by_orientation(list, group_sizes: [2,3], vertical_method: :video_vertical?).each do |decorated_item|
      - item = decorated_item[:item]
      .col.aesn-flex-order style=('width: 100%' unless item.video_vertical?) data-flex-order=decorated_item[:sizes][2] data-sm-flex-order=decorated_item[:sizes][3]
        = aesn_video_tag *item.exercise.video_sources_with_meta(:width), style: 'width: 100%; height: auto;', autoplay: true, muted: true, loop: true, poster: item.exercise.video_url(:screenshot)

app/views/sport/activities/edit.slim
.container-fluid
  = render 'shared/obj', obj: @page
  = render 'sport/activities/form', activity: @sport_activity, kinds: @kinds

= javascript_pack_tag 'has_many_fields', 'data-turbolinks-track': 'reload'

app/views/sport/activities/index.slim
.container-fluid
  = render 'shared/obj', obj: @page
  .row.justify-content-center
    .btn-group
      = link_to "Мои тренировки из strava", strava_activities_path, class: 'btn btn-primary btn-lg px-4 gap-3'
  .row.row-cols-1.row-cols-sm-2.row-cols.md-3.g-3.mt-2
    - @sport_activities.each do |activity|
      .col
        .card.shadow-sm
          .card-header = activity.kind
          .card-body
            h2.card-title = activity.name
            - if activity.duration
              .card-text = l(activity.duration, format: '%T')
            = render 'sport/activities/provider_list', list: activity.provider_activities

            .d-flex.justify-content-between.align-items-center.mt-1
              .btn-group
                = link_to 'Подробнее', sport_activity_path(activity), class: 'btn btn-sm btn-outline-secondary'
              small.text-muted = l(activity.started_at, format: :short)
  = paginate @sport_activities, theme: 'bootstrap-5'

app/views/sport/activities/new.slim
.container-fluid
  = render 'shared/obj', obj: @page
  = render 'sport/activities/form', activity: @sport_activity, kinds: @kinds

= javascript_pack_tag 'has_many_fields', 'data-turbolinks-track': 'reload'

app/views/sport/activities/show.slim
.container-fluid
  = render 'shared/obj', obj: @page, hide_content: true

  .px-4.py-5.my-5
    .card
      .card-header
        .d-flex.justify-content-between.align-items-center
          h1 = "#{@resource.kind} — #{@resource.name}"
          = render 'sport/activities/show_actions', activity: @resource, dropdown_id: 'sport-activity-show-actions'
      - if @resource.provider_activities.present?
        .card-body
          h2.card-title От #{Russian.p(@resource.provider_names.size, "провайдера", "провайдеров", "провайдеров")} #{@resource.provider_names.to_sentence}
          = render 'sport/activities/provider_list', list: @resource.provider_activities
  = render 'sport/activities/video_gallery', list: @resource.activity_exercises_with_video